kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqcl4route 
  namespace: mq 
spec:
  host: tlsfour.chl.mq.ibm.com
  to:
    kind: Service
    name: mqcl4-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
