kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqcl1route 
  namespace: ibmmq 
spec:
  host: tlsthree.chl.mq.ibm.com
  to:
    kind: Service
    name: mqcl3-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
