apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mqcl4
  namespace: mq
spec:
  license:
    accept: true
    license: L-RJON-BZFQU2
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    image: cp.icr.io/cp/ibm-mqadvanced-server-integration:9.2.3.0-r1-amd64
    imagePullPolicy: Always
    storage:
      queueManager:
        enabled: true
    availability:
     type: SingleInstance
#     type: NativeHA
    name: CL4
    mqsc:
    - configMap:
        name: cl4-mqsc
        items:
        - cl.mqsc
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.2.3.0-r1
  web:
    enabled: true
  tracing:
    enabled: false
    namespace: od
  pki:
    keys:
      - name: label1
        secret:
          secretName: mqcl4key
          items:
            - tls.key
            - tls.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
