apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mqcl4
  namespace: mq
spec:
  license:
    accept: true
    license: L-CYPF-CRPF3H
    use: Production
  queueManager:
    imagePullPolicy: Always
    storage:
      queueManager:
        enabled: true
    resources:
      limits:
        cpu: '0.3'
        memory: 1Gi
      requests:
        cpu: '0.3'
        memory: 1Gi
    availability:
     type: SingleInstance
#     type: NativeHA
    name: CL1
    mqsc:
    - configMap:
        name: cl4-mqsc
        items:
        - cl.mqsc
    ini:
    - configMap:
        name: cl4-mqsc
        items:
        - mq.ini
  version: 9.4.3.1-r3
  web:
    enabled: true
  pki:
    keys:
      - name: label1
        secret:
          secretName: mqcl4key
          items:
            - tls.key
            - tls.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
