apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mqcl4
  namespace: mq
spec:
  license:
    accept: true
    license: L-JTPV-KYG8TF
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    storage:
      defaultClass: ocs-storagecluster-cephfs
      queueManager:
        type: persistent-claim
    resources:
      limits:
        cpu: '0.3'
        memory: 1Gi
      requests:
        cpu: '0.3'
        memory: 1Gi
    availability:
     #type: SingleInstance
      type: NativeHA
    name: CL4
    mqsc:
    - configMap:
        name: cl4-mqsc
        items:
        - cl.mqsc
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.4.0.0-r1
  web:
    enabled: true
  pki:
    keys:
      - name: label1
        secret:
          secretName: mqcl4key
          items:
            - tls.key
            - tls.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
